apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ingress-restricted
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-url: http://authorization.default.svc.cluster.local:8000/verify
    nginx.ingress.kubernetes.io/auth-response-headers: Authentication
spec:
  rules:
    - host: api.dev.pepeunlimited.com
      http:
        paths:
          - backend:
              serviceName: todo
              servicePort: 80
            path: /twirp/pepeunlimited.todo.TodoService/*
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-todo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://nginx-jwt.ingress-nginx.svc.cluster.local:8000/verify
spec:
  rules:
    - host: api.dev.pepeunlimited.com
      http:
        paths:
          - backend:
              serviceName: todo
              servicePort: 80
            path: /twirp/pepeunlimited.todo.TodoService/CreateTodo